services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: myapi-container

    ports:
      - "5035:5035"

    environment:
      ASPNETCORE_HTTP_PORTS: 5035

    depends_on:
      - postgres

    networks:
      - myapp-network


  postgres:
    image: postgres:17

    container_name: postgres-db

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - myapp-network


networks:
  myapp-network:


volumes:
  postgres-data:
    external: true